### ISSUE TITLE
`SerilogTracing.Instrumentation.SqlClient` requests

### ISSUE THREAD

**Issue by viceroypenguin** [serilog-tracing/serilog-tracing#100]
I have explored adding `SerilogTracing` to my app, and I love it, including the `SerilogTracing.Instrumentation.SqlClient`. However, the problem I run into is that Hangfire makes db queries once/second. While I don't mind HF making these queries, logging them is unnecessary and overwhelming. 

One path to addressing this for me would be two requests:
* Add `command.Connection.Credential.UserId` to the list of properties being logged
* Add a Filter property to the `SqlCommandActivityInstrumentationOptions` which would be a callback returning `false` if the current log entry should not be logged.

However, I'm open to other potential solutions, if there is a better path that makes sense.

Thanks @nblumhardt!

**Comment by nblumhardt** [comment]
Hi @viceroypenguin, thanks for the feedback and notes!

RE adding `UserId`, that sounds good to me; open to a PR if you or anyone watching might be interested in putting it together, otherwise I'll leave this ticket open to track it.

RE the filter callback, I believe the `new ActivityListenerConfiguration().Sample.Using(...)` callback should be able to achieve this. I'm not sure how hard it will be to identify which spans are being triggered by Hangfire but keen to hear whether this looks like a promising direction to explore.

**Comment by viceroypenguin** [comment]
Few things:
1. The credential is only populated if you populate it directly, it is not populated from the connection string. This makes it effectively useless in modern C# development.
2. I mixed up how I am distinguishing Hangfire connections from regular connections - I am using the Application Name property, which I can use on the SQL server to filter to only app connections and ignore the HF connections. 
3. The Application Name is _also_ not available except by parsing the connection string.
4. Would you be open to a configuration that allows adding the Connection String as a Property, with the default of `false` (for security reasons)?

**Comment by viceroypenguin** [comment]
5. It does not appear that any of the `ActivityInstrumentation.SetLogEventProperty` data is available inside of the `Sample.Using(...)` lambda, so I'm not sure how to make it useful. Thoughts?

**Comment by nblumhardt** [comment]
Thanks for the follow-ups!

RE adding `ConnectionString` as a property, perhaps this could be done using a general "enrich" callback, the way that `options.GetRequestProperties` can be used in _SerilogTracing.Instrumentation.AspNetCore_?

RE `Sample.Using`, there's very little available context, unfortunately, as this callback fires before an `Activity` instance is created.

Along with the activity source name (this will have to match the _SqlClient_ instrumentation one), and very general parent activity information, the only things I think you can use to detect Hangfire will be ambient/static.

If you have any way of hooking into Hangfire ahead of it checking its queue, wrapping it in a block that sets and then un-sets some kind of `[ThreadStatic]` `InHangfire` variable could work (you'd then check the varable in the callback).

Or, if Hangfire uses a single worker thread in a loop for queue checking, you may be able to check the current thread's name in the callback.

I don't know enough about Hangfire to suggest any other options, but there will be a way, somehow :-) ... keen to hear what you find!

**Comment by viceroypenguin** [comment]
NB: any idea when #106 will be on nuget? I'll probably want information from the SqlCommand for filtering...

**Comment by nblumhardt** [comment]
Hi @viceroypenguin - thanks for all the feedback. That change is in the 1.1.0-dev-* versions on NuGet.org now, it'd be great to hear how it goes for you. RTM is just around the corner :+1: 

> Is this due to how serilog tracing is set up, or due to how the existing Activity stuff is set up? There's no way to add a filter based on data that's been added to the context, then.

This is based on an `Activity` API; the callback happens before the activity is created, to save cycles and allocations, so at the point sampling occurs there's very little to go on, except static/async-local state.

> What about adding a filter on the sink? By that I mean, let the Activity stuff process normally, but adding a filter to decide whether the activity gets sent to Seq or the console, etc? I suppose I could use .Filter.ByExcluding(...) on the logger itself, and then find the attached properties from the activity... I'll ponder this and come back when I figure something out.

Filtering out spans is okay if they're "leaves" in the trace tree; if you filter out a span, and that span has children, the children won't be correctly placed in the resulting trace. It sounds like you should be safe enough using that approach in this scenario.

**Comment by viceroypenguin** [comment]
@nblumhardt I got it working. 

For reference for anyone looking here later:

#### Creating ALC
```cs
new ActivityListenerConfiguration()
	.Instrument.AspNetCoreRequests()
	.Instrument.SqlClientCommands(o =>
	{
		o.GetCommandProperties = cmd =>
		[
			new LogEventProperty("SqlCommandText", new ScalarValue(cmd.CommandText)),
			new LogEventProperty("SqlDatabase", new ScalarValue(cmd.Connection.Database)),

			new LogEventProperty(
				"SqlApplicationName",
				new ScalarValue(
						new SqlConnectionStringBuilder(cmd.Connection.ConnectionString)
							.ApplicationName
					)
				),
		];

		o.MessageTemplate = "Executed SQL";
	})
	.TraceToSharedLogger();
```

#### Filtering Hangfire
```cs
.Filter.ByExcluding(
	Matching.WithProperty<string>(
		"SqlApplicationName",
		sv => sv.StartsWith("Hangfire", StringComparison.Ordinal)
	)
)
```
