### ISSUE TITLE
Configure Through App Settings

### ISSUE THREAD

**Issue by plexbox** [serilog-tracing/serilog-tracing#101]
Do you have an example of configuring the message templates with vscode coloring through appsettings?

**Comment by nblumhardt** [comment]
Hi Eric,

I don't think this is possible as things stand today - the closest you'd get is:

https://stackoverflow.com/questions/66550450/how-to-use-expression-template-with-appsettings-in-serilog

and creating a custom template based on the one used internally by the `Formatters` class in this repo. I don't think it's possible to specify the custom name resolver to enable functions like `IsSpan()`, though you can probably emulate those with `isdefined(@st)` kinds of things.

HTH,
Nick
