### ISSUE TITLE
Sql Instrumentation Include Table Name in Template

### ISSUE THREAD

**Issue by SeanMartz** [serilog-tracing/serilog-tracing#102]
Hello - thanks for all the amazing work that's gone into this!

I was wondering if it made sense to include update the SqlInstrumentation Template. 

I wrote a quick enricher with some regex to attempt to parse the table name that's being queried and I wanted to append it to the template, so that I could more easily understand my traces in SEQ.  But since there is not MessageTemplate property of the `SqlCommandActivityInstrumentationOptions` the only way I could see to do it was to overwrite the `Database` property.

If there's interest, I'd be happy to make a PR to include a MessageTemplate in `SqlCommandActivityInstrumentationOptions`. 

Additionally - would there be any interest in including the Table Name Parsing into the Instrumentation as a built in feature?

There could be a use case like mine, or perhaps as a slight enrichment to the span without including the full CommandText.

Thanks for your consideration!

``` csharp
public class SQLTableNameEnricher : ILogEventEnricher
{
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        if (logEvent == null)
            throw new ArgumentNullException(nameof(logEvent));
        if (propertyFactory == null)
            throw new ArgumentNullException(nameof(propertyFactory));
        LogEventPropertyValue eventPropertyValue;

        if (!logEvent.Properties.TryGetValue("SourceContext", out eventPropertyValue))
            return;

        var sqlClient = new ScalarValue("SerilogTracing.Instrumentation.SqlClient");

        if (!eventPropertyValue.Equals(sqlClient))
            return;

        if (!logEvent.Properties.TryGetValue("CommandText", out var commandText))
            return;

        var match = Regex.Match(commandText.ToString(), @"(?:from|into)\s+((\[?\w+\]?\.\[?\w+\]?\.\[?\w+\]?)|(\[?\w+\]?\.\[?\w+\]?)|(\[?\w+\]?))",
            RegexOptions.IgnoreCase);
        if (!match.Success)
            return;

        var tableName = match.Groups[1].Value;

        // Overwriting Database because we can't specify the template for the SQL Client Instrumentation
        logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty("Database", (object) tableName));
    }
}
```

![image](https://github.com/serilog-tracing/serilog-tracing/assets/12223671/fdb1bd1d-84c3-4cd3-b538-73535e311715)

**Comment by nblumhardt** [comment]
Hi @SeanMartz thanks for dropping by!

@viceroypenguin opened #100 with a related request (including `ConnectionString` in `SqlClient` spans), I was thinking perhaps we could handle both of these cases by introducing an API similar to the one used in _SerilogTracing.Instrumentation.AspNetCore_ to allow message template and property customization:

```csharp
    /// <summary>
    /// The message template to associate with request activities.
    /// </summary>
    public string MessageTemplate { get; set; } = DefaultRequestCompletionMessageTemplate;

    /// <summary>
    /// A function to populate properties on the activity from an incoming request.
    /// This closure will be invoked at the start of the request pipeline.
    /// </summary>
    public Func<HttpRequest, IEnumerable<LogEventProperty>> GetRequestProperties { get; set; } = DefaultGetRequestProperties;
```

In the `SqlClient` case I think the argument to the callback would be `SqlCommand`, which provides access to the connection etc.

What do you think? And is anyone following along interested in putting a PR together?

**Comment by nblumhardt** [comment]
Example of what I mean, for the `HttpClient` instrumentation: https://github.com/serilog-tracing/serilog-tracing/pull/103 :-)
