### ISSUE TITLE
Try to use filters

### ISSUE THREAD

**Issue by roberto-gaxiola** [serilog-tracing/serilog-tracing#107]
Hi, im starting to use c# and  im trying to filter some RequestPath from seq, but its ignoring my filters, here's my program.cs

`

using Serilog;
using Serilog.Context;
using Serilog.Events;
using Serilog.Exceptions;
using SerilogTracing;
using Serilog.Debugging;

    var logger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .Enrich.WithExceptionDetails()
    .Enrich.WithProperty("Application", typeof(Program).Assembly.GetName().Name)
    .WriteTo.Logger(l =>
    {
        l.Filter.ByExcluding("RequestPath like '/health%' and StatusCode < 400");
        l.Filter.ByExcluding("RequestPath like '/ui%'");
        l.Filter.ByExcluding("RequestPath like '/dashboard%'");
        l.Filter.ByExcluding("RequestPath like '/hangfire%'");
        l.Filter.ByExcluding("RequestPath like '/swagger%'");
        l.Filter.ByExcluding("RequestPath like '/favicon%'");
        l.Filter.ByExcluding("RequestPath like '/index%'");
        l.Filter.ByExcluding("RequestPath like '/'");
        l.WriteTo.Seq(seqUrl, apiKey: seqKey);
    })
    .CreateLogger();

    using var _ = new ActivityListenerConfiguration()
        .Instrument.AspNetCoreRequests()
        .TraceToSharedLogger();
`

if i remove the activitylistenerconfiguration, it works ok, but as soon as i add, it ignores my filters.

**Comment by nblumhardt** [comment]
Hi @roberto-gaxiola,

In the snippet, you don't appear to be initializing the shared logger (`Log.Logger`), but the activity listener is using `TraceToSharedLogger()`.

Either assigning `Log.Logger`, or using `TraceTo(logger)`, would seem to make more sense here.

**Comment by robertogaxiola** [comment]
I changes the ckde to use Log.logger ibstead off a logger and still the filters don't work

**Comment by nblumhardt** [comment]
Hi! What do the events in Seq look like? (Expanded view of an event you expected to be filtered out, showing its properties.)

Posting an updated and more complete code snippet would also help. Cheers!

**Comment by robertogaxiola** [comment]
This is the new code:

`Log.Logger = new LoggerConfiguration()
.Enrich.FromLogContext()
.Enrich.WithExceptionDetails()
.Enrich.WithProperty("Application", typeof(Program).Assembly.GetName().Name)
.WriteTo.Logger(l =>
{
    l.Filter.ByExcluding("RequestPath like '/health%' and StatusCode < 400");
    l.Filter.ByExcluding("RequestPath like '/ui%'");
    l.Filter.ByExcluding("RequestPath like '/dashboard%'");
    l.Filter.ByExcluding("RequestPath like '/hangfire%'");
    l.Filter.ByExcluding("RequestPath like '/swagger%'");
    l.Filter.ByExcluding("RequestPath like '/favicon%'");
    l.Filter.ByExcluding("RequestPath like '/index%'");
    l.Filter.ByExcluding("RequestPath like '/'");
    l.WriteTo.Seq(seqUrl, apiKey: seqKey);
})
.CreateLogger();

using var _ = new ActivityListenerConfiguration()
    .Instrument.AspNetCoreRequests()
    .TraceToSharedLogger();
    
builder.Host.UseSerilog(Log.Logger);
    `
    
    and here is a image of the result in seq
    
    
![SNAG 2024-05-30 0001](https://github.com/serilog-tracing/serilog-tracing/assets/47841846/47534c08-9fc7-4b39-93ea-713a687a5111)

**Comment by nblumhardt** [comment]
Thanks for the extra info. That was one tough bug! Found the cause, sending a PR now 👍
