### ISSUE TITLE
How to use expressions in instrumentation message template?

### ISSUE THREAD

**Issue by ricardoboss** [serilog-tracing/serilog-tracing#111]
I would expect the expression in the following code to work, but it doesn't:

```csharp
_ = new ActivityListenerConfiguration()
    .Instrument.AspNetCoreRequests(o =>
    {
        o.MessageTemplate = "HTTP {RequestMethod} {RequestPath}{#if QueryString is not null}{QueryString}{#end} -> {StatusCode}";
    })
    .TraceToSharedLogger();
```

Are expressions not supported in instrumentations?

**Comment by nblumhardt** [comment]
Hi Ricardo; although they're syntactically similar, [message templates](https://messagetemplates.org) (which are used for capturing as well as formatting) are separate from [expression templates](https://github.com/serilog/serilog-expressions) (which are used for formatting only).

**Comment by ricardoboss** [comment]
Ahh, so I can only use message templates in that case?

I guess I can normalize the `QueryString` to an empty string if null...

**Comment by nblumhardt** [comment]
I think if it's missing it'll already be omitted from the output; that's the general solution though 👍

**Comment by ricardoboss** [comment]
Unfortunately if `QueryString` is `null`, it gets converted to the string "null".

So the message ends up as "HTTP POST /hellonull -> 200"

**Comment by nblumhardt** [comment]
Thanks for the follow-up; normalizing sounds like the way to go 👍
