### ISSUE TITLE
Question - is it possible to save traces using file sink?

### ISSUE THREAD

**Issue by OndrejMus** [serilog-tracing/serilog-tracing#118]
Hello there, I would like to use tracing in new project, but my limitation is that there is not back-end that could receive traces in target environments. For logs, I can user file sink and move files to different environment, where I can import files to Seq. 

I have not option to install Seq or other tools in target environment and file is easy and reliable way for persisting logs (and hopefully traces) for transfer and investigation in different environment.

Is there some option to save traces using file sink so they can be imported to Seq using clef.exe?

Thank you for amazing work :)

**Comment by nblumhardt** [comment]
Hi Ondrej,

It's possible to use Serilog.Sinks.File with the [`SeqCompactJsonFormatter` class from Serilog.Sinks.Seq](https://github.com/datalust/serilog-sinks-seq/blob/dev/src/Serilog.Sinks.Seq/Sinks/Seq/SeqCompactJsonFormatter.cs#L36) - after installing that package, pass a `new SeqCompactJsonFormatter()` in the first argument position of the `WriteTo.File()` method.

The resulting files will be in Seq's ingestion API format, including traces, which can be HTTP `POST`ed to `/ingest/clef` on the Seq server. I believe `seqcli ingest` should be able to do this, but I'm not 100% sure it's compatible and can't check just now - if you have trouble getting the files into Seq, just let me know here and I'll dig around :-)
