### ISSUE TITLE
Surface `ActivityEvent`s as `LogEvent`s

### ISSUE THREAD

**Issue by Seb-FS-Axpo** [serilog-tracing/serilog-tracing#121]
Hi,

I have started using SerilogTracing to gather traces from sub-components (internal /external libraries). Thanks for this, this is quite neat ! 

Some of the Activities defined in those components uses the [AddEvent](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs#optional-add-events) method instead of creating child activities.

After doing a bit of testing it seems the activity events are not translated into Serilog LogEvent, if I am not mistaken (I am also using Serilog 3 and SerilogTracing 1.1 for now on as some components are using older .Net framework). 

Any chance this would be supported in (near/the) future ?

Thanks :)

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. I think because (in my limited experience) the events attached to spans can be very low-quality/noisy, this isn't something we'd want to switch on by default, but an `ActivityListenerOption` for it seems reasonable.

Any chance you can let me know what libraries you're consuming spans from, and what the events generally look like?

I'll dig in now and let you know what I come up with.

**Comment by Seb-FS-Axpo** [comment]
Thanks for such a fast feedback !

I like the option approach and to be fair the events I was mentioning are from internal libraries. 
I am not sure if part of the public libraries we are using, any are taking advantage of the `ActivityEvents` :( 

In our case when child-activities are not used, public methods of a particular class will start their own activity and in order to get more granular tracing, this activity will be passed as parameter to private methods, as one would do to share a regular logger instance from one component to another.

From there the `activity.AddEvent` method is used to kind of highlight (important|some) steps in the execution flow.

```csharp
public Task<IEnumerable<Record>> GetTimeSeriesRecords (int id, LocalDate quoteDate){
{
    using (Activity activity = _activitySource.StartActivity("Retrieving time series records"))
    {
        var details = new Dictionary<string, object> {
          { "time series id", id },
          { "quote date", quoteDate }
        }

        activity?.SetTag("time series details", details);

        var query = await BuildUpTimeSeriesSQLQuery(id, quoteDate, activity);
        var queryOutput = await ExecuteTimeSeriesSQLQuery(query, activity);        
        return await ConvertOutput(queryOutput, activity);
    }
}

private Task<Query> BuildUpTimeSeriesSQLQuery (int id, LocalDate quoteDate, Activity activity){
    ...
    activity?.AddEvent(new ActivityEvent("Building up time series SQL query"))
    ...
}

private Task<QueryOutput> ExecuteTimeSeriesSQLQuery(Query query, Activity activity){
    ...
    activity?.AddEvent(new ActivityEvent("Executing time series SQL query"))
    activity?.SetTag("SQL query", query.ToString())
    ...
}
```

This looks quite basic, hope this still helps

**Comment by nblumhardt** [comment]
That's great, thanks :+1:

**Comment by Seb-FS-Axpo** [comment]
Awesome. Thanks a lot for such support :)
