### ISSUE TITLE
Properties["ParentSpanId"] being set but not showing up in Seq

### ISSUE THREAD

**Issue by bmontalvoDD** [serilog-tracing/serilog-tracing#123]
I have a Web API project that receives input via POST and creates queue messages to be processed by a worker service. I am creating a LoggerActivity and passing it's Id with the queue message data. When my worker service picks up the queue message, it creates it's own LoggerActivity and calls AddProperty("ParentSpanId", parentSpanIdFromApi) but the ParentSpanId is not being seen by Seq, it's not even showing up in the Properties. Is there something I'm missing?

**Comment by nblumhardt** [comment]
Hi @bmontalvoDD,

The `ParentSpanId` property is only recognized if the value is an `ActivitySpanId`, not a string, so you may need to do this conversion before setting it.

For "plumbing" scenarios like this, you might alternatively just use the `ActivitySource.StartActivity(..., ActivityContex)` API directly, to create that outermost span. Trace propagation is an important scenario for SerilogTracing, but the APIs to support it are a little rough right now (as you've found :-)). Let me know if you need any info on what this approach would look like.

**Comment by bmontalvoDD** [comment]
Hi @nblumhardt your suggestion worked! Thank you
