### ISSUE TITLE
Microsoft.Extension.Logging `ILogger<T>` Possible Implementation

### ISSUE THREAD

**Issue by Meigs2** [serilog-tracing/serilog-tracing#128]
Hello!

I was investigating adding spans/tracing to my logs, and this library came up. However, my app uses `ILogger<T>` and not serilog's `ILogger` and saw #75. 

I was going to settle on just using the static logger via an extension method, however this has some issues, mainly that the static logger doesn't capture the `SourceContext` alone, and if you try to augment the static logger by doing `.ForContext<T>()` it returns a different `SourceContext` value than the regular `Logger<T>` implementation. This is a bummer. I took a crack at this today over lunch and I think I've found a way to get it working, with some tradeoffs.

The big issue that you need to work around is that the Microsoft `Logger<T>` implementation uses the internal function `TypeNameHelper.GetTypeDisplayName` in `Microsoft.Extenions.Internal` to get the display name of the class to be used in the `SourceContext`. So, one option here is to simply use reflection to call the `Logger<T>`'s internal static method to get the name of a type. Honestly, this might be a fine solution.

However, there's a less reflective way to achieve the same result via DI. You can actually create two classes: A custom `ILogger<T>` and a wrapper class delegating the creation of the `ILoggerFactory` used by the standard `Logger<T>`. The wrapper then tracks what the `Logger<T>` determined the class name to be, and you use an extension method on `ILogger<T>` to check if the logger is our wrapper, and if so reach in through the Logger wrapper and factory wrapper to get the underlying `Serilog.Logger` instance.

It's a bit hard to understand without code, so here's my (trimmed down for GitHub) example code. This won't compile as-is, but the core idea is all here:

```csharp
public class LoggerWrapper<T> : ILogger<T>
{
    private readonly LoggerFactoryWrapper<T> _wrapper;
    private Logger<T> _logger;

    public LoggerWrapper(LoggerFactoryWrapper<T> wrapper)
    {
        _wrapper = wrapper;
        _logger = new Logger<T>(wrapper);
    }

    // ... delegate implementation methods to `_logger` here

    public Serilog.ILogger GetActivityLogger()
    {
        return _wrapper.GetSerilogLogger();
    }
}

public class LoggerFactoryWrapper<T> : ILoggerFactory
{
    private Serilog.ILogger _logger;
    private ILoggerFactory _factory;
    private string _categoryName;

    public LoggerFactoryWrapper(Serilog.Ilogger logger, ILoggerFactory factory)
    {
        _logger = logger; // Serilog logger, as resolved by DI
        _factory = factory; // The ACTUAL factory is resolved here
    }

    public ILogger CreateLogger(string categoryName)
    {
        _categoryName = categoryName; // Record category name!
        return _factory.CreateLogger(categoryName);
    }

    // Restore `SourceContext` as created by Microsoft's `Logger<T>`.
    public Serilog.ILogger GetSerilogLogger() => _logger.ForContext(Constants.SourceContextPropertyName, _categoryName);

    // Rest of delegated impl
}

public static class Extensions
{
    public static IServiceCollection UseActivityLogger(this IServiceCollection services)
    {
        services.AddSingleton(typeof(SerilogLoggerFactoryWrapper<>)); // Register wrapper class, this does not interfere with registration of `ILoggerFactory`!
        services.AddSingleton(typeof(ILogger<>), typeof(ActivityLogger<>)); // Replace standard Logger<T> with ours that accepts the factory wrapper
    }

    // Method to be used by an instance of an `ILogger<T>`
    public static LoggerActivity StartActivity<T>(this ILogger<T> logger, string messageTemplate)
    {
        if (logger is LoggerWrapper<T> activityLogger) // Check type, if it's our wrapper we can get the underlying Serilog logger.
            return activityLogger.GetActivityLogger().StartActivity(messageTemplate);
        return Log.Logger.ForContext<T>().StartActivity(messageTemplate);
    }
}
```

When DI resolves the `ILogger<T>`, it's going to use our wrapper type. ***We then pass the wrapper to a standard `Logger<T>`, which will eventually call `CrateLogger` with the correctly formatted type name.*** The wrapper exposes a method to get the serilog logger passed in via DI. All `UseSerilog` and `AddSerilog` add `Serilog.ILogger` as a Singleton, so this is always available. Because the logger needs to be created before we can call `StartActivity<T>`, we know that the `Logger<T>` will have invoked `CreateLogger `, recording the `_categoryName` before we ever call `GetSerilogLogger()`, so it should be safe at that point. To make this safer, you can make these classes internal or private in the package to prevent direct use.

With these wrappers, all you have to do is check the type of the ILogger<T>. If it's of the wrapper type, you can call `GetActivityLogger` to get the underlying serilog logger, otherwise just assume the global logger. This should work for basically everyone, except people injecting a non-global instance of `Serilog.ILogger` to be used in DI, which I can't imagine is that many people. The downside to this method is performance, but I haven't benchmarked it, but I doubt it would be that bad.

If the repo is accepting PR's, I wouldn't mind submitting one this weekend for a `SerilogTracing.Extensions.Logging` package or similar. Otherwise, feel free to use this idea if the maintainers want to add support for `Microsoft.Extensions.Logging`.

Thanks :)

**Comment by Meigs2** [comment]
Oops, quick clarification, `Logger<T>` actually calls on the passed in factory directly in it's constructor, meaning we can guarantee we resolve and record the name before we can get the inner Serilog logger.

See: https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerT.cs#L29

**Comment by nblumhardt** [comment]
Hi Connor, thanks for posting this, and sorry about the slow reply (traveling last week).

I don't think adding support for MEL is in scope for this project currently, but it's been a popular request so, at worst, hopefully your sample above will unblock some people.

If you're keen to publish a separate/independent package for this and post a link here, that would also be awesome.

Thanks again!
