### ISSUE TITLE
Persisting enrichments throughout the activity like LoggerExtensions.BeginScope

### ISSUE THREAD

**Issue by HaydenReeve** [serilog-tracing/serilog-tracing#129]
Hello 👋

I was surprised that the StartActivity call didn't persist enrichments through its scope.

I was imaging, when first looking over the detail here, that it would function somewhat similarly to `LoggerExtensions.BeginScope`

Instead, I've found myself constantly leaning into a double using at the start of each activity using a `PushProperty` scope to keep enrichments in memory, which is quite a mouthful of boilerplate each time.

Is there a limitation that would prevent the implementation of persistent enrichments here? It would be very nice to, say, write something akin to

```C#
using LoggerActivity scope = logger.StartActivity("Requested to do the thing by {Requester}", someUsername);

logger.Information("An action was performed as a result");
```

Ideally I'd like to see `someUsername` enrich the log message emitted immediately following.

To achieve this, you instead need to use

```C#
using IDisposable context = LogContext.PushProperty("Requester", someUsername);
using LoggerActivity scope = logger.StartActivity("Requested to do the thing by {Requester}", someUsername);

logger.Information("An action was performed as a result");
```

Is it possible to opt into the properties in the `StartActivity` being persisted throughout the scope? Such as a new overload `StartScopedActivity` or something similar?

**Comment by nblumhardt** [comment]
Thanks for this suggestion, too. It's also something I'd suggest building a custom extension method to support for now. It's a nice usage pattern for some kinds of apps but one that would be implemented and tuned at a higher layer while we focus on the fundamental APIs in this library.

**Comment by nblumhardt** [comment]
Closing this as we're not planning to take action on it, but the ticket can still serve as a note to our future selves :-)
