### ISSUE TITLE
Add option to customize activities from ActivityListener like is already possible with DiagnosticListener

### ISSUE THREAD

**Issue by ngbrown** [serilog-tracing/serilog-tracing#138]
(copied from https://github.com/serilog-tracing/serilog-tracing/issues/34#issuecomment-2392857057)

When an instrumented library starts and ends an activity, the trace text message is not going to be templated. When the library uses `DiagnosticSource` to start activities I can customize SerilogTracing with `ActivityListenerConfiguration.Instrument`. Currently `IActivityInstrumentor` requires `DiagnosticListener` to be used by the library providing the instrumentation.

An example implementation of `IActivityInstrumentor` with a custom template is `SerilogTracing.Instrumentation.AspNetCore`. The HTTP template text is here: https://github.com/serilog-tracing/serilog-tracing/blob/8305fd5ae843a7d48733265baf7692d7c007ba40/src/SerilogTracing.Instrumentation.AspNetCore/Instrumentation/AspNetCore/HttpRequestInActivityInstrumentationOptions.cs#L25-L26

I am trying to integrate with the new `ActivitySource` instrumentation available in v7 of RabbitMQ.Client (now at ver 7.0.0-rc.11).

This matters because the default trace log text does not show in Seq as following a template, so every different queue or channel received from or sent on results in a different message type:

![Screenshot 2024-10-03 220346](https://github.com/user-attachments/assets/d5c0096a-eb6f-4e1f-8dcb-62d0765ead41)

I initially went down the path of trying to implement something similar to what was done for `SerilogTracing.Instrumentation.SqlClient`, but came to the realization that the RabbitMQ.Client isn't using `DiagnosticListener`/`DiagnosticSource` at all, so `IActivityInstrumentor.ShouldSubscribeTo` is never called using a RabbitMQ related `diagnosticListenerName`.

This does seems to be following the guidance from the .NET team because their 2020 design decision says they are simplifying the recommended pattern of activity objects to [not use `DiagnosticSource`](https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/activity-improvements.md#:~:text=We%20are%20simplifying%20the%20pattern%20to%20something%20like%3A). 

I can inject my own message template overrides for SerilogTracing if I setup my own `ActivityListener`, but this relies on the ordering of calls to subscribers, so doesn't seem like a great idea.

<details>
<summary>Expand for Program.cs. See AddAmqpActivityInterceptor() for a roundabout way to inject custom templates and assign parameters to Activities about to be sent to Seq.</summary>

```cs
using System.Diagnostics;
using GrpcGreeter.Services;
using Serilog;
using Serilog.Events;
using Serilog.Parsing;
using Serilog.Templates.Themes;
using SerilogTracing;
using SerilogTracing.Expressions;
using SerilogTracing.Instrumentation;

namespace GrpcGreeter;

public class Program
{
    // Works in the console, but Seq (as of 2024.3.12250) doesn't yet seem to support this
    const bool UseDottedPropertyNames = false;

    public static void Main(string[] args)
    {
        AppContext.SetSwitch("Serilog.Parsing.MessageTemplateParser.AcceptDottedPropertyNames", UseDottedPropertyNames);

        Log.Logger = new LoggerConfiguration()
            .Enrich.WithProperty("Application", typeof(Program).Assembly.GetName().Name)
            .WriteTo.Console(Formatters.CreateConsoleTextFormatter(TemplateTheme.Code))
            .WriteTo.Seq("http://localhost:5341")
            .CreateLogger();

        try
        {
            var builder = WebApplication.CreateBuilder(args);

            // Additional configuration is required to successfully run gRPC on macOS.
            // For instructions on how to configure Kestrel and gRPC clients on macOS, visit https://go.microsoft.com/fwlink/?linkid=2099682

            AddAmqpActivityInterceptor();

            // Add services to the container.
            builder.Services.AddSerilog();
            builder.Services.AddSingleton(
                new ActivityListenerConfiguration()
                    .Instrument.AspNetCoreRequests()
                    .Instrument.RabbitMQClient()
                    .TraceToSharedLogger());
            builder.Services.AddGrpc();

            builder.Services.AddSingleton<FibService>();
            builder.Services.AddHostedService<RabbitMqServer>();

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            app.MapGrpcService<GreeterService>();
            app.MapGet("/",
                () =>
                    "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

            app.Run();
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Application terminated unexpectedly");
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

    private static void AddAmqpActivityInterceptor()
    {
        var messageTemplateSubscriber =
            new MessageTemplateParser().Parse(UseDottedPropertyNames
                ? "AMQP {messaging.operation} {messaging.rabbitmq.destination.routing_key}"
                : "AMQP {Operation} {RoutingKey}");
        var messageTemplatePublisher =
            new MessageTemplateParser().Parse(UseDottedPropertyNames
                ? "AMQP {messaging.operation} {messaging.destination.name}"
                : "AMQP {Operation} {DestinationName}");

        var activityListener = new ActivityListener
        {
            ShouldListenTo = source =>
                source.Name == "RabbitMQ.Client.Subscriber" ||
                source.Name == "RabbitMQ.Client.Publisher",
            ActivityStopped = OnActivityStopped
        };
        ActivitySource.AddActivityListener(activityListener);
        return;

        void OnActivityStopped(Activity activity)
        {
            if (activity.Source.Name == "RabbitMQ.Client.Subscriber")
            {
                ActivityInstrumentation.SetMessageTemplateOverride(activity, messageTemplateSubscriber);
                foreach (var (k, v) in activity.Tags)
                {
                    switch (k)
                    {
                        case "messaging.operation":
                            ActivityInstrumentation.SetLogEventProperty(
                                activity,
                                UseDottedPropertyNames ? k : "Operation",
                                new ScalarValue(v));
                            break;
                        case "messaging.rabbitmq.destination.routing_key":
                            ActivityInstrumentation.SetLogEventProperty(
                                activity,
                                UseDottedPropertyNames ? k : "RoutingKey",
                                new ScalarValue(v));
                            break;
                    }
                }
            }
            else if (activity.Source.Name == "RabbitMQ.Client.Publisher")
            {
                ActivityInstrumentation.SetMessageTemplateOverride(activity, messageTemplatePublisher);
                foreach (var (k, v) in activity.Tags)
                {
                    switch (k)
                    {
                        case "messaging.operation":
                            ActivityInstrumentation.SetLogEventProperty(
                                activity,
                                UseDottedPropertyNames ? k : "Operation",
                                new ScalarValue(v));
                            break;
                        case "messaging.destination.name":
                            ActivityInstrumentation.SetLogEventProperty(
                                activity,
                                UseDottedPropertyNames ? k : "DestinationName",
                                new ScalarValue(v));
                            break;
                    }
                }
            }
        }
    }
}
```
</details>

So now Seq shows a templated trace:

![Screenshot 2024-10-03 222317](https://github.com/user-attachments/assets/998cf56b-868b-43e9-b87e-9aa4417fe63b)

But because Seq doesn't seem to support `AcceptDottedPropertyNames` property yet, I end up with duplicate properties to support the templating in Seq:

![Screenshot 2024-10-03 222454](https://github.com/user-attachments/assets/b2d9b1fd-82e1-4a21-ba95-1bb4f92c19a9)

So what I'm asking for is a way to do set a custom template and properties on a to-be logged trace (an `Activity` that came from `ActivitySource`) somewhere around https://github.com/serilog-tracing/serilog-tracing/blob/8305fd5ae843a7d48733265baf7692d7c007ba40/src/SerilogTracing/Interop/LoggerActivityListener.cs#L115-L119 or within [`ActivityConvert`](https://github.com/serilog-tracing/serilog-tracing/blob/8305fd5ae843a7d48733265baf7692d7c007ba40/src/SerilogTracing/Interop/ActivityConvert.cs#L25).

My test project is available on the `rabbit-rpc` branch here: https://github.com/ngbrown/grpc-testing/commits/rabbit-rpc/

**Comment by ngbrown** [comment]
@nblumhardt and @KodrAus Do you want me to submit a pull request to add `SerilogTracing.Instrumentation.RabbitMQ` to this repository?

It would mostly just be what is here: https://github.com/ngbrown/grpc-testing/tree/with-serilog-tracing-pr/SerilogTracing.Instrumentation.RabbitMQ but without the `throw new NotImplementedException`.

**Comment by KodrAus** [comment]
@ngbrown That sounds great to me!

**Comment by nblumhardt** [comment]
Likewise; looks awesome 👍
