### ISSUE TITLE
How can I add tracing to .NET Framework MVC requests?

### ISSUE THREAD

**Issue by norr-carr** [serilog-tracing/serilog-tracing#145]
I'm trying to add tracing to a legacy Framework 4.8 MVC application.  We already use Serilog, Seq, and SerilogWeb.Classic enrichers.  I'd really like to be able to do something similar to .Instrument.AspNetCoreRequests() where we could have requests automatically start activities for each request.  I have been able to manually create trace activities in my MVC application.  Do I have to create a global action filter or HttpModule to start trace activities?  Or is there a more automatic way to accomplish this?

For example, here's my basic Framework 4.8 MVC setup in Global.asax.cs:
```
protected void Application_Start()
{
	var log = new LoggerConfiguration()
		.WriteTo.Seq("http://localhost:5341")
		.Enrich.WithHttpRequestId()
		.CreateLogger()
		.ForContext<MvcApplication>();
	Log.Logger = log;

	AreaRegistration.RegisterAllAreas();
	FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
	RouteConfig.RegisterRoutes(RouteTable.Routes);
	BundleConfig.RegisterBundles(BundleTable.Bundles);
}
```
This does not produce any trace information. I can start activities within the controllers though, which does produce trace information.

**Comment by nblumhardt** [comment]
Hi! I think the `Application_BeginRequest()` and `_EndRequest()` events will be the place to start; e.g. in the begin method, start an activity, and complete it in the end method:

```csharp
protected void Application_BeginRequest(object sender, EventArgs e)
{
    HttpContext.Current.Items["SerilogTracingActivity"] = Log.Logger.StartActivity("HTTP request");
}

protected void Application_EndRequest(object sender, EventArgs e)
{
    var activity = HttpContext.Current.Items["SerilogTracingActivity"] as LoggerActivity;
    if (activity != null)
    {
        activity.Complete();
    }
}
```

(I'm not on a Windows machine right now so you might need to tweak this a bit to get it running.)

The `StartActivity()` call will need some details from `HttpContext.Current`.

Before completing the activity you might add some properties to it such as the final status code and exception, if any; `Application_Error()` might need to be handled in order to reliably get the exception:

```csharp
protected void Application_Error(object sender, EventArgs e)
{
    var ex = Server.GetLastError();
    // Stash `ex` in `HttpContext.Current.Items` and retrieve in _EndRequest
}
```

You could move all of this to a module, but getting started in `Global.asax` directly will need fewer moving parts.

Keen to hear how you go!

**Comment by norr-carr** [comment]
Thank you Nicholas that worked great for me!  I added your suggestions to my dotnet framework MVC template application.  Here it is for anyone's future reference:
Global.asax
```
using Serilog;
using SerilogTracing;
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Optimization;
using System.Web.Routing;
using Serilog.Events;

namespace TracingApp
{
	public class MvcApplication : System.Web.HttpApplication
	{
		const string serilogTracingException = nameof(serilogTracingException);

		protected void Application_Start()
		{
			var log = new LoggerConfiguration()
				.WriteTo.Seq("http://localhost:5341")
				.Enrich.WithHttpRequestId()
				.CreateLogger()
				.ForContext<MvcApplication>();
			Log.Logger = log;
			Log.Logger.Information("Hello - Application_Start"); //Works

			AreaRegistration.RegisterAllAreas();
			FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
			RouteConfig.RegisterRoutes(RouteTable.Routes);
			BundleConfig.RegisterBundles(BundleTable.Bundles);
		}

		protected void Application_BeginRequest(object sender, EventArgs e)
		{
			using (var listener = new ActivityListenerConfiguration().TraceToSharedLogger())
			{
				HttpContext.Current.Items["SerilogTracingActivity"] = Log.Logger.StartActivity("HTTP request {0}", HttpContext.Current.Request.RawUrl);
			}
		}

		protected void Application_EndRequest(object sender, EventArgs e)
		{
			{
				var activity = HttpContext.Current.Items["SerilogTracingActivity"] as LoggerActivity;
				var ex = HttpContext.Current.Items[serilogTracingException] as Exception;
				if (activity != null)
				{
					if (ex != null)
						activity.Complete(LogEventLevel.Error, ex);
					else
						activity.Complete();
				}
			}
		}

		protected void Application_Error(object sender, EventArgs e)
		{
			HttpContext.Current.Items[serilogTracingException] = Server.GetLastError();
		}
	}
}
```

HomeController
```
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Serilog;
using SerilogTracing;

namespace TracingApp.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			using (var activity = this.HttpContext.Items["SerilogTracingActivity"] as LoggerActivity)
			{
				Log.Logger.Information("Hello - Index start");
				return View();
			}
		}

		public ActionResult Error()
		{
			using (var activity = this.HttpContext.Items["SerilogTracingActivity"] as LoggerActivity)
			{
				Log.Logger.Error("Something went wrong!");
				throw new Exception("Oh no!");
			}
		}
        }
}
```

**Comment by nblumhardt** [comment]
Thanks for the follow-up! Couple of suggestions -

The `using (var activity = ...` bits in the controller actions shouldn't be necessary, the activities there are the same ones that will be completed in the `_EndRequest` handler, so all those blocks are doing is completing them early (and therefore hiding the time taken to render views/suppressing capturing of exceptions thrown during view rendering).

In `Application_BeginRequest`, this line is configuring then tearing down SerilogTracing each time:

```csharp
using (var listener = new ActivityListenerConfiguration().TraceToSharedLogger())
```

I think what's needed instead is to remove this and instead store the same listener in the application class's static properties for the lifetime of the application.

So just beneath the `const` declaration up the top you'd add `static IDisposable serilogTracingActivityListener;`, and then in `_Start`, initialize it once the logger is initialized:

```csharp
                        // No need for a separate `log` variable
			Log.Logger = new LoggerConfiguration()
				.WriteTo.Seq("http://localhost:5341")
				.Enrich.WithHttpRequestId()
				.CreateLogger();

                        // The `Log` class exposes `ForContext` and `Information` directly
			Log
                            .ForContext<MvcApplication>()
                            .Information("Hello - Application_Start");

                        // Configured only once, and used for the whole application
                        serilogTracingActivityListener = new ActivityListenerConfiguration()
                            .TraceToSharedLogger();

                         // Area registration, etc.
```

HTH!

**Comment by norr-carr** [comment]
Thank you!  Do you happen to know if .Instrument.SqlClientCommands() should work with Entity Framework 6?

**Comment by nblumhardt** [comment]
Currently no, AFAIK - the instrumentation is based on the Microsoft.Data.SqlClient package, and I suspect EF6 uses System.Data.SqlClient. It should be possible to copy and modify the instrumentation but some experimentation would be required.

**Comment by norr-carr** [comment]
Thanks again Nicholas, this was super helpful.  I did find out that it's possible to switch EF6 from System.Data.SqlClient to Microsoft.Data.SqlClient, but our current code didn't work after making that change so I did add some activities manually around the data context save.

**Comment by nblumhardt** [comment]
👍

**Comment by pfaustinom1** [comment]
Hello there! I'm also trying to achieve the same, with global.asax (plus OWIN) and I've a question:

> I think what's needed instead is to remove this and instead store the same listener in the application class's static properties for the lifetime of the application.
> 
> So just beneath the `const` declaration up the top you'd add `static IDisposable serilogTracingActivityListener;`, and then in `_Start`, initialize it once the logger is initialized:
> 
>                         // No need for a separate `log` variable
> 			Log.Logger = new LoggerConfiguration()
> 				.WriteTo.Seq("http://localhost:5341")
> 				.Enrich.WithHttpRequestId()
> 				.CreateLogger();
> 
>                         // The `Log` class exposes `ForContext` and `Information` directly
> 			Log
>                             .ForContext<MvcApplication>()
>                             .Information("Hello - Application_Start");
> 
>                         // Configured only once, and used for the whole application
>                         serilogTracingActivityListener = new ActivityListenerConfiguration()
>                             .TraceToSharedLogger();
> 
>                          // Area registration, etc.
> HTH!

Are we required to call `serilogTracingActivityListener.Dispose()` somewhere? @norr-carr did you dispose it in the `Application_End()` method?

**Comment by nblumhardt** [comment]
Hi @pfaustinom1 ! It's okay leaving the activity listener un-disposed; disposing it unhooks some event handlers, but at application shutdown this isn't a big worry.

If you're able to cleanly dispose it on shutdown that would probably be nice, remembering that as soon as it is disposed, traces won't be captured anymore.

Cheers!
