### ISSUE TITLE
Traces not logged from DI services when `Microsoft` log level not set to `Information` 

### ISSUE THREAD

**Issue by stephenpope** [serilog-tracing/serilog-tracing#146]
## Scenario

Nuget Version: `2.2.0`

I am trying to get timings back for some services inside a web API application, I am not using `Seq` but just wanting to see the traces in the console log.

To eliminate some noise I am setting the `Microsoft` log level to `Warning`.

When I do this any traces that are configured with a service inside the container will not show when `Microsoft` is not set to `Information`.

### Repro

Basic setup and test trace ..
```csharp
var loggerConfiguration = new LoggerConfiguration()
        .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
        .Enrich.WithProperty("Environment", builder.Environment.EnvironmentName)
        .WriteTo.Console(formatter);

Log.Logger = loggerConfiguration.CreateLogger();

using var listener = new ActivityListenerConfiguration().TraceTo(Log.Logger); 

using var startupActivity = Log.Logger.StartActivity("Startup");

builder.Services.AddTransient<ITestService, TestService>();

startupActivity.Complete();
```

Results in 
```
[14:18:33 INF] └─ Startup (1.144 ms)
```

When I trigger an endpoint to invoke the service e.g.
```
app.MapGet("/test", (ITestService service) => { service.DoThing(); }
```
Nothing is displayed in the log (Activity is `null`).

Setting the `Microsoft` log level to `Information`, I get the output I'm expecting.

```
[14:33:00 INF] └─ Startup (1.061 ms)
[14:33:01 INF] ┊ Now listening on: http://localhost:5064
<snip lots of junk output>
[14:33:07 INF] ├─ Service Thing (0.123 ms)
```

Even setting the explicit namespace of my service in the `.MinimumLevel.Override` does not effect it.

This is my first time using this libary so I am fully aware this could be my lack of understanding. If anything I was struggling to find which namespace it thinks the calls are coming from to filter them.

Thanks for looking :)

**Comment by stephenpope** [comment]
Added `.Instrument.AspNetCoreRequests()` and this fixed it. Sorry about that.

**Comment by nblumhardt** [comment]
Glad you found a solution - thanks for the follow-up, @stephenpope.

Another option is to be more specific about the minimum level overrides; most of the noise can be cut using:

```csharp
    .MinimumLevel.Override("Microsoft.AspNetCore.Hosting", LogEventLevel.Warning)
    .MinimumLevel.Override("Microsoft.AspNetCore.Routing", LogEventLevel.Warning)
```

without silencing all `Microsoft.*` output.

There's a bit more info on how all of this fits together in https://nblumhardt.com/2024/04/serilog-net8-0-minimal/. HTH!
