### ISSUE TITLE
No traces in Zipkin when running the example weather and Example.WeatherService

### ISSUE THREAD

**Issue by rachkoud** [serilog-tracing/serilog-tracing#149]
Hi,

I have installed Zipkin which is running fine on http://localhost:9411/ : 

`docker run -d -p 9411:9411 openzipkin/zipkin
`

I started the example : 

- https://github.com/serilog-tracing/serilog-tracing/tree/dev/example/weather
- https://github.com/serilog-tracing/serilog-tracing/tree/dev/example/Example.WeatherService

I can see the trace in Seq : 

![image](https://github.com/user-attachments/assets/85d8abf1-91c3-4d4d-a9ea-4d4385a94fe5)

But nothing in Zipkin.

I put a breakpoint in `ZipkinSink` : 

```csharp
public async Task EmitBatchAsync(IEnumerable<LogEvent> batch)
    {
        var content = FormatRequestContent(batch);
        if (content == null)
            return;

        var request = new HttpRequestMessage(HttpMethod.Post, "api/v2/spans")
        {
            Content = new StringContent(content, _encoding, "application/json")
        };

        var response = await _client.SendAsync(request);
        response.EnsureSuccessStatusCode();
    }
```

And saw that I had an error in the response 400 BadRequest : 

`Expected a long but was 1730464198558327.4 at line 1 column 176 path $[0].timestamp reading List<Span> from json`

I find out the problem was here `TracingFunctions` and commented (decimal)ts.Ticks / 10 : 

  public static LogEventPropertyValue? Microseconds(LogEventPropertyValue? timeSpan)
  {
      // Casts (truncates) rather than rounding.
      // if (timeSpan is ScalarValue { Value: TimeSpan ts })
      //     return new ScalarValue((decimal)ts.Ticks / 10);

      if (timeSpan is ScalarValue { Value: TimeSpan ts })
          return new ScalarValue((decimal)ts.Ticks);
      
      return null;
  }

Now I'm getting a 202 but there is nothing in Zipkin : 

![image](https://github.com/user-attachments/assets/b4333cd3-4462-43e4-9059-09fde5fa94d8)

I'm new to OpenTelemetry and don't why I can't see the traces in Zipkin?

There is no error in Docker also : 

```bash
docker logs c72c664eea47975477f16627b05afb43088bbb52af650b3b11203092544af0f2

                  oo
                 oooo
                oooooo
               oooooooo
              oooooooooo
             oooooooooooo
           ooooooo  ooooooo
          oooooo     ooooooo
         oooooo       ooooooo
        oooooo   o  o   oooooo
       oooooo   oo  oo   oooooo
     ooooooo  oooo  oooo  ooooooo
    oooooo   ooooo  ooooo  ooooooo
   oooooo   oooooo  oooooo  ooooooo
  oooooooo      oo  oo      oooooooo
  ooooooooooooo oo  oo ooooooooooooo
      oooooooooooo  oooooooooooo
          oooooooo  oooooooo
              oooo  oooo

     ________ ____  _  _____ _   _
    |__  /_ _|  _ \| |/ /_ _| \ | |
      / / | || |_) | ' / | ||  \| |
     / /_ | ||  __/| . \ | || |\  |
    |____|___|_|   |_|\_\___|_| \_|

:: version 3.4.2 :: commit ac5a965 ::

2024-11-01T10:26:03.188Z  WARN [/] 1 --- [           main] i.m.p.PrometheusMeterRegistry            : A MeterFilter is being configured after a Meter has been registered to this registry. All MeterFilters should be configured before any Meters are registered. If that is not possible or you have a use case where it should be allowed, let the Micrometer maintainers know at https://github.com/micrometer-metrics/micrometer/issues/4920. Enable DEBUG level logging on this logger to see a stack trace of the call configuring this MeterFilter.
2024-11-01T10:26:03.345Z  INFO [/] 1 --- [oss-http-*:9411] c.l.a.s.Server                           : Serving HTTP at /[0:0:0:0:0:0:0:0]:9411 - http://127.0.0.1:9411/
```

**Comment by KodrAus** [comment]
Thanks for the report @rachkoud! It looks like Zipkin's API expects the timestamp as an integer value of microseconds since the Unix epoch.

The behavior of that `Microseconds` expression doesn't appear to actually truncate to a whole integer value so I think this is a bug.
