### ISSUE TITLE
Resolution of `EndTime` is lower than `StartTime` on .NET Framework, causing some invalid activity durations

### ISSUE THREAD

**Issue by fredrik-dfind** [serilog-tracing/serilog-tracing#151]
When using `Serilog.Log.Logger.StartActivity` to start new activities we sometime and up with activities where `StartTime` is later than `EndTime`, for very short activities. Seq does not like this at all.

Seems like the code uses the `StartTime `from `System.Diagnostics.Activity` and `DateTimeOffset.Now` for the `EndTime`. `System.Diagnostics.Activity` has a much more accurate time than `DateTimeOffset.Now`. Microsoft have also experienced this same issue.

This is how I've solved the problem... for now? :)

```
static Profiler()
{
    Listner = new ActivityListener()
    {
        ShouldListenTo = (source) =>
            source.Name == SerilogTracing.Core.Constants.SerilogTracingActivitySourceName,
        ActivityStarted = (activity) =>
            activity.SetStartTime(DateTimeOffset.Now.UtcDateTime)
    };
    ActivitySource.AddActivityListener(Listner);
}
```

**Comment by nblumhardt** [comment]
Hi @fredrik-dfind - are you running your application on .NET Framework or .NET (Core)? There are some differences between these so it'd be good to pin down which behavior we're hitting. Thanks for the report!

**Comment by nblumhardt** [comment]
On .NET Framework, `Activity.Start()` uses the following time source: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.DateTime.netfx.cs

**Comment by fredrik-dfind** [comment]
Here is the issue I mentioned: https://github.com/dotnet/runtime/issues/45111

We're on .NET Core, or more specifically net8.0-windows

**Comment by fredrik-dfind** [comment]
Apologies, we're currently upgrading to net8.0. 
This problem was discovered in .NET Framework 4.8

**Comment by nblumhardt** [comment]
Ah thanks! 👍
