### ISSUE TITLE
Always apply the parent precedence sampler in `Sample.Using`

### ISSUE THREAD

**Issue by KodrAus** [serilog-tracing/serilog-tracing#163]
I can't think of a valid case where you "upgrade" the sampling decision of an activity using a sampler. If you do, you're almost certainly going to end up with a broken trace. I think we should therefore always wrap a given sampler in our parent precedence check, so that a given sampler is only called when it makes sense to do so.

This would be a breaking behavioural change, but I believe it works around an issue and the rules around how and when samplers are called are mushy enough that I think it's reasonable to do.

**Comment by nblumhardt** [comment]
Perhaps with an opt-out? E.g. `Sample.Using(mySampler, ignoreParent: true)` or similar?
