### ISSUE TITLE
Parent precedence should handle case where Activity.Current is null

### ISSUE THREAD

**Issue by KodrAus** [serilog-tracing/serilog-tracing#164]
If you're manually injecting tracing context using `Logger.StartActivity`, you can pass in an `ActivityContext` as its remote parent, but don't have any way to specify that parent context is meant to be remote, meaning our "is remote" check in the parent precedence sampler falls through and we may incorrectly mark future activities as recorded.

I think we should also check if `Activity.Current == null` in here, so we at least propagate its sampling decision if we're given a parent context, but there's no current activity:

```csharp
if (options.Parent != default)
{
    // The activity is a child of another; if the parent is recorded, the child is recorded. Otherwise,
    // as long as a local activity is present, there's no need to generate an activity at all.
    return (options.Parent.TraceFlags & ActivityTraceFlags.Recorded) == ActivityTraceFlags.Recorded ?
        ActivitySamplingResult.AllDataAndRecorded :
        options.Parent.IsRemote || Activity.Current == null ?
            ActivitySamplingResult.PropagationData :
            ActivitySamplingResult.None;
}
```

**Comment by nblumhardt** [comment]
> don't have any way to specify that parent context is meant to be remote

Is the normal case here that the parent context will have been created by the caller? If so, the `isRemote` constructor parameter should be enough:

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycontext.-ctor?view=net-9.0

**Comment by KodrAus** [comment]
Yes indeed :+1: I missed that constructor argument because was using `ActivityContext.Parse`.
