### ISSUE TITLE
.NET Standard 2 compatibility

### ISSUE THREAD

**Issue by srogovtsev** [serilog-tracing/serilog-tracing#22]
I've noticed that _SerilogTracing` is currently .NET 6+ compatible: https://github.com/serilog-tracing/serilog-tracing/blob/7d5e7088d5a424bceee77e70b4befd965c452dc2/src/SerilogTracing/SerilogTracing.csproj#L4

Would it be possible to target the .NET Standard 2 as well? I don't think there should be technical issues with that (both Serilog and otel support it, same as [`System.Diagnostics.DiagnosticSource`](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/)).

P.S. Believe it or not, some of us are still on .NET Framework.

**Comment by nblumhardt** [comment]
The plan so far has been to add it (and possibly `net462`) once the general API/feature set has settled, but PRs welcome in the meantime if anyone's interested in giving it a shot :+1:

**Comment by pfaustinom1** [comment]
Does the library support .NET Framework projects with the new updates for .NET Standard 2.0? I have copied the console example to a .NET Framework 4.8 project, but the logs in Seq are not associated to any trace.

**Comment by nblumhardt** [comment]
Hi @pfaustinom1; yes, as far as we're aware there aren't any bugs preventing use of the netstandard2.0 version on 4.8. Could you please open a new ticket with details of your SerilogTracing configuration, and the Seq version you're running? Thanks!
