### ISSUE TITLE
(Option to) render messages used as `Activity.Description`

### ISSUE THREAD

**Issue by nblumhardt** [serilog-tracing/serilog-tracing#27]
When Serilog events are exposed as `Activity` instances, we currently set the activity description to the message template.

This isn't especially nice to use:

![image](https://github.com/serilog-tracing/serilog-tracing/assets/342712/de34f27e-7d51-472d-b1b2-e34d637abd01)

I think either opting in or out of rendering the full message to these will be necessary:

![image](https://github.com/serilog-tracing/serilog-tracing/assets/342712/0fe35062-e069-4e36-a9f6-474f6456122e)

**Comment by srogovtsev** [comment]
Unfortunately, this goes against OpenTelemetry standard. It [states](https://opentelemetry.io/docs/specs/otel/trace/api/#span) that "Generality SHOULD be prioritized over human-readability" and examples specifically shows that `get_account/42` is "too specific" and "get_account/{accountId}" should be preferred.

So while this is "nice to use", this is something that current tooling does _not_ expect. Here's why (screenshot from Jaeger):

![image](https://github.com/serilog-tracing/serilog-tracing/assets/2332517/4b5037bc-e0d9-4f83-996c-a76bea5fd7af)

All the operations will be listed here for filtering; rendering the parameters will make this list unusable.

(on the other hand, implementing this on side of Seq can make a good winning point)

**Comment by nblumhardt** [comment]
Closing this; I don't think we'll want to change how the activity description is populated; we may want to reconsider how the OTLP sink handles this also, but I'll do that via a separate ticket. Thanks!
