### ISSUE TITLE
`TracingConfiguration.EmitTo.*` to replace `ILogger` argument of `EnableTracing()`

### ISSUE THREAD

**Issue by nblumhardt** [serilog-tracing/serilog-tracing#36]
`TracingConfiguration` currently sets up the activity listener to write events through to the static `Log.Logger` by default.

This can be changed by passing an `ILogger` to `EnableTracing()`, but since the rest of the API is now fluent, it's not very discoverable or consistent keeping this argument here.

`EmitTo.Logger(ILogger)` and `EmitTo.StaticLogger()` might be reasonable names to use?

On semantics, the default should still be to write to the static logger. Serilog configuration usually allows defaults to be re-specified, for better or worse.

There's only a single target logger to configure, so last in will win.

**Comment by srogovtsev** [comment]
Frankly, for me setting this as a parameter of `EnableTracing` seems most logical. "You want to trace it? Show me where to trace it!"

**Comment by nblumhardt** [comment]
Doing it via `EnableTracing()` might work better if we renamed that method to two variants - `TraceTo(ILogger)` and `TraceToSharedLogger()`
