### ISSUE TITLE
Add a `StartActivity()` on `Microsoft.Extensions.Logging.ILogger`

### ISSUE THREAD

**Issue by viceroypenguin** [serilog-tracing/serilog-tracing#48]
For many consumers, such as myself, Serilog is the primary factory, but MSL is the primary interface used to generate log messages. Having `StartActivity()` as an option on MSDI `ILogger` would ease adoption instead of having to replace all existing DI infrastructure to use Serilog.ILogger instead of MSL

**Comment by nblumhardt** [comment]
Hi @viceroypenguin!

I'd love to be able to do this, but I don't think there's a clear path to it in the current codebase, at least without a serious amount of design and re-thinking 🤔 ...

In the short term, if you're keen on the "application-friendly" tracing API that SerilogTracing provides, one option you might find useful is to create a custom, generic, `ITracer<T>` interface (emulating `ILogger<T>`), and put a `StartActivity()` method on it matching the SerilogTracing one (with a few supporting types required).

You could then implement the interface directly over the underlying Serilog logger, but avoid the need to introduce a second logging abstraction into your code.

The other option, of course, is to just depend on `System.Diagnostics.Activity`'s tracing API, and build your own `ActivityListener` that converts completed activities into log events in whatever pipeline you choose. Not a trivial undertaking, either, but worth considering.

Hope this helps,
Nick

**Comment by nblumhardt** [comment]
I'll close this one as "not planned", but keen to hear where you land if you explore this direction further!

**Comment by viceroypenguin** [comment]
Note for anyone attempting to do this, the following code works in net8.0 (and likely all the way back to netcoreapp3.1). 

> [!WARNING]  
> This relies on implementation details of both `Microsoft.Extensions.Logging` as well as `Serilog.Extensions.Logging`; there is no guarantee this code will work in the future.

> [!WARNING]  
> This relies on reflection, which is not fast. Future versions of this code may rely on `[UnsafeAccessor]`, which should be faster but the generics involved increase minimum requirement to net9.0 (which is still in preview as of this writing).

```cs
public static LoggerActivity? StartActivity<T>(this ILogger<T> logger, string messageTemplate, params object?[]? propertyValues)
{
	if (logger is not Logger<T> l)
		return null;

	if (GetLogger(GetLogger(l)) is not Serilog.ILogger serilogLogger)
		return null;

	return serilogLogger.StartActivity(messageTemplate, propertyValues);
}

private static object? GetLogger(object? o)
{
	if (o is null) return null;

	var loggerMemberInfo = o.GetType().GetField("_logger", BindingFlags.Instance | BindingFlags.NonPublic);
	var innerLogger = loggerMemberInfo!.GetValue(o);
	return innerLogger;
}
```
