### ISSUE TITLE
1.0.0 Release Tasks

### ISSUE THREAD

**Issue by nblumhardt** [serilog-tracing/serilog-tracing#57]
- [x] #55 
 - [x] #44
 - [x] #31
 - [x] Split out sinks and instrumentation that will version separately from the core
 - [x] README update for instrumentors
 - [x] README update for SQL client instrumentation
 - [x] README update for initial levelling mechanism
 - [x] Decide on #61 
 - [x] Baseline benchmarking

**Comment by KodrAus** [comment]
A combination of high and low level benchmarking of the overhead of our listener for both instrumented and non-instrumented activities would be good to know too ahead of calling this 1.0

**Comment by nblumhardt** [comment]
RE splitting out projects that will version separately, I think that effectively means setting up separate repositories for all subprojects. Even ones that we'll want to "1.0" in the near future will need to evolve separately at some point.

**Comment by nblumhardt** [comment]
We changed direction on splitting out repos; going to get to 1.0 with a monorepo (-lite :-)) and work forward from there.
