### ISSUE TITLE
TracingConfiguration is confusingly named

### ISSUE THREAD

**Issue by KodrAus** [serilog-tracing/serilog-tracing#61]
The `TracingConfiguration` and the infrastructure it sets up only applies to activities created outside of SerilogTracing's `ILogger.StartActivity()`. This isn't obvious from its name though, and gets confusing when options seem like they should apply to SerilogTracing activities too, but don't.

I think we should rename the type to `ExternalTracingConfiguration`.

**Comment by nblumhardt** [comment]
I initially reached for `ActivityListenerConfiguration` (accurate but perhaps not obviously related to "tracing"?) and thought about `TraceListenerConfiguration` (maybe better but incorrectly alludes to some relationship with the old trace listener mechanism)...

The "external" prefix is decent but it's not really clear prima facie what the "external" is external _to_ - could be external as in where we're sending the traces, or external as in distributed traces propagating in and out from other systems 🤔

**Comment by KodrAus** [comment]
That might be less of an issue if we can define what _external activity_ means, but I think `ActivityListenerConfiguration` is also pretty good. Perhaps we can find a decent name by thinking about how we'd explain what it does?

> Activities started by `ILogger.StartActivity()` will be emitted as log events on completion. SerilogTracing can also emit log events for activities started by standard `ActivitySource`s too. To configure a listener for these activities, use `ActivityListenerConfiguration.TraceTo(ILogger)`.
