### ISSUE TITLE
ASP.NET Core instrumentation isn't producing traces by default

### ISSUE THREAD

**Issue by Suchiman** [serilog-tracing/serilog-tracing#67]
Hard to come up with a fitting title, i've been experimenting with this stuff because all of the blog posts made me excited but i'm not sure if i'm holding it right. After upgrading seq, upgrading nugets and installing the SerilogTracing libs + adding
```csharp
            using var _ = new ActivityListenerConfiguration()
                .Instrument.AspNetCoreRequests()
                .Instrument.SqlClientCommands()
                .TraceToSharedLogger();
```
as well as changing `WriteTo.Seq(...)` to `WriteTo.SeqTracing` i've noticed no change, other than the log events now have a `Trace (...)` option in seq. Clicking on that and using `Show` brings up nothing without any explanation as to why.
![image](https://github.com/serilog-tracing/serilog-tracing/assets/7110884/697d0c13-4a2e-483a-bd8f-28a197a1243f)
digging around in the API requests i found this query text being sent that comes back empty handed
```sql
select coalesce(@Resource.service.name, Application, 'unknown_service') as serviceName, 
        @Message as message, 
        @Level as level, 
        @TraceId as traceId, 
        @SpanId as spanId, 
        @ParentId as parentId, 
        TotalMilliseconds(@Elapsed) as elapsedMs,
        ToIsoString(@Start) as start, 
        ToIsoString(@Timestamp) as timestamp,
        @Start as startTick,
        @Timestamp as timestampTick
        
        from stream 
        where Has(@Start) and Has(@SpanId) and @TraceId = '8bcad354512a096b58a7adb8cc051597'
```
playing around with that i've figured that the reason for this is that none of the events have the magic `@Start` property, whose presence or absence you can see nowhere in seq as far as i could tell.
I did expect to get some builtin tracing, especially after enabling Instrumentation for SqlClient and ASP.NET Core but in lack thereof, i went ahead and added `using var activity = Log.Logger.StartActivity("Selecting Verträge");`  to a random API.
Now i do get something in the trace view, even builtin ones
![image](https://github.com/serilog-tracing/serilog-tracing/assets/7110884/8b717bdc-e418-4c66-8d94-7f0c712ee46a)
not sure why `SQL SELECT` is not being printed without me having to add `StartActivity`.
Also not sure why this says missing 
![image](https://github.com/serilog-tracing/serilog-tracing/assets/7110884/754dcd4e-1e4e-4efd-8356-ce9bcf2c0c70)
I went looking in the example apps to check if i did miss something obvious but didn't really find anything. I was confused that the example app configures both SeqTracing and OpenTelemetry, this is not necessary, is it?
https://github.com/serilog-tracing/serilog-tracing/blob/b5f5a490758b3b3f4c3d6786e450a810b0ffca87/example/Example.WeatherService/Program.cs#L12-L14
I've also been using `App` consistently across all services for the application name, saving on those 8 bytes ('App' vs. 'Application') for every log, i guess i'll have to rename that now?

**Comment by nblumhardt** [comment]
Thanks for all the feedback!

Are you running this on .NET Core or Framework, and which version? (The need to explicitly create an activity is surprising, sounds like we've missed something there - could be related to the incoming request including an unrecorded parent trace id. Will investigate!)

The example app definitely needs some trimming back now that the major pieces are built, we've been using it as a quick and easy smoke test, but it should probably be split into several different examples now, for different sinks.

There's a way to get around the `App` issue for now (also something we're considering making configurable on the Seq side), I'll reply with an example shortly.

**Comment by Suchiman** [comment]
> Are you running this on .NET Core or Framework, and which version? (The need to explicitly create an activity is surprising, sounds like we've missed something there - could be related to the incoming request including an unrecorded parent trace id. Will investigate!)

It's an ASP.NET Core 8 app, still using Startup.cs, providing a Controller based API (and MVC views).

**Comment by KodrAus** [comment]
Thanks for trying this out and for the feedback @Suchiman! 🙇

I don't know for certain yet, but have a suspicion that missing span is an activity generated by ASP.NET Core and has the `Recorded` trace flag set to `false`, which it will be unless the client explicitly sends a traceparent header where it's `true`. We use this flag to decide whether to record an activity or not and I think we might be treating this flag too aggressively. We can't actually tell the difference between `Recorded == false` meaning no decision has been explicitly made and `Recorded == false` meaning don't record.

**Comment by nblumhardt** [comment]
Another possibility, do you have a `MinimumLevel.Override("Microsoft.AspNetCore", ...)`?

If so, does removing this (or making it more specific) sort things out?

**Comment by Suchiman** [comment]
> Another possibility, do you have a `MinimumLevel.Override("Microsoft.AspNetCore", ...)`?
> 
> If so, does removing this (or making it more specific) sort things out?

I did have it set to Warning (in appSettings.json), since i'm using the concise "one message per request" serilog package, suspected that that might be an issue so i've removed it (with default log level set to verbose), but that didn't help (but certainly spammed the log)

**Comment by nblumhardt** [comment]
Hi Robin; we've tracked this down to how flags from incoming `traceparent` headers are handled; we have a solution in progress but expect it'll take another few days to get into `dev`. We'll keep you posted!

**Comment by Suchiman** [comment]
> Hi Robin; we've tracked this down to how flags from incoming `traceparent` headers are handled; we have a solution in progress but expect it'll take another few days to get into `dev`. We'll keep you posted!

Awesome, thanks Nick! No worries

**Comment by halcharger** [comment]
I experience the same lack of clarity, waiting for the PR to go through.

**Comment by KodrAus** [comment]
As of `1.0.0-dev-00225` `SerilogTracing.Instrumentation.AspNetCore` will now handle the incoming `traceparent` headers differently, with the difference being it will more likely emit spans by default. With no configuration, we'll now:

1. Respect any incoming trace id and parent span id
2. Ignore any trace flags (so potentially malicious clients, or those not sending any traceparent headers can't disable instrumentation on your behalf)
3. Ignore baggage (to limit the potential for accidental context propagation or misuse)

You can change this behavior through the `IncomingTraceParent` enum. It also allows complete disregard for any incoming traceparent (suitable for public APIs) or complete respect for incoming traceparent including sampling and baggage (suitable for exclusively internal APIs).

.NET has APIs around `DistributedContextPropagator` for controlling this stuff, but we wanted to offer a simple and more direct API around managing this if you're using `SerilogTracing.Instrumentation.AspNetCore`.

I'd love to hear how you go with this, and any more feedback you have!

**Comment by halcharger** [comment]
Hi,

I'm not sure if this is the correct email to reply on (apologies if it
isn't). I'm struggling to find an example (in your example folder) of how
to configure my application to use *IncomingTraceParent.Ignore*, please
could you advise?

Regards,
Allen.

**Comment by nblumhardt** [comment]
Hi @halcharger; it should be:

```csharp
    .Instrument.AspNetCoreRequests(opts => opts.IncomingTraceParent = IncomingTraceParent.Ignore)
```

This should sort out the major source of problems with this right behavior right now, however we've spotted one other thing (the default sampler is using `AllData` but should instead be `AllDataAndRecorded`) which we'll fix before closing this issue.

Let us know if you still don't get the behavior you want with `IncomingTraceParent.Ignore`, though :-)

Best regards,
Nick

**Comment by halcharger** [comment]
Ok, so I added in `IncomingTraceParent.Ignore` however this still didn't result in traces coming through into my Seq instance. So I thought I'd simply try your actual example code and see if that pushed traces through, and it didn't either. Here's what I did:

I updated and ran your example code like so:

![image](https://github.com/serilog-tracing/serilog-tracing/assets/111745/bfa29ec5-2e48-4acd-a5b7-78630c7a7d9b)

Then ran the api and hit the postcode endpoint like so:

![image](https://github.com/serilog-tracing/serilog-tracing/assets/111745/8f702cae-2452-49b0-af0a-a9cfee31f854)

Looked in my Seq instance for traces but found none, I found logs, but no traces:

![image](https://github.com/serilog-tracing/serilog-tracing/assets/111745/13175480-e88a-4df6-807b-9f11d0983964)

So it's not clear to me what I'm doing wrong, especially since I'm using the official example.

**Comment by nblumhardt** [comment]
Thanks for the follow-up, @halcharger.

That "HTTP GET /4000" event is a span; does it have a little "timing bar" in its right margin? If so, clicking it will reveal the trace.

If not, do you see a "Show" option when you drop down its "Trace (..)" menu item?

Thanks!

**Comment by halcharger** [comment]
Embarrassingly enough I've just discovered the Trace link in the screenshot I posted and found the tracing feature, my bad, thanks for the help. :-(

**Comment by nblumhardt** [comment]
I think that's probably our bad! Good to know that there are still some discoverability issues for us to work out there, appreciate the feedback 👍

**Comment by Suchiman** [comment]
> There's a way to get around the App issue for now (also something we're considering making configurable on the Seq side), I'll reply with an example shortly.

So btw.... did you figure out an workaround 😁? Or is the configuration comming soon(TM)?

**Comment by nblumhardt** [comment]
Hi @Suchiman; I'd meant to suggest using a custom (`ExpressionTemplate`-based) `ITextFormatter` with the Seq sink to copy `App` into `service.name` - something like:

```csharp
    .WriteTo.Seq("http://localhost:5341", payloadFormatter: new ExpressionTemplate(
        "{ {@t, @mt, @l: if @l = 'Information' then undefined() else @l, @x, @sp, @tr, @ps: ParentSpanId, @st: SpanStartTimestamp, @sk: SpanKind, App, service: {name: App}, ..rest()} }\n"))
```

This will, unfortunately, leave you with a redundant/additional `service.name` property on the Seq side.

I think a bit further down the track, a system setting to allow custom expressions for service names is on the cards (currently seq uses `coalesce(service.name, Application)`).

**Comment by Suchiman** [comment]
> I think a bit further down the track, a system setting to allow custom expressions for service names is on the cards (currently seq uses `coalesce(service.name, Application)`).

Yeah that'd be preferrable, right now we have like 20 apps, each of them having an `Enrich.WithProperty("App", "SomeName")` hardcoded (for localhost seq purposes). In addition to that, each App is deployed to ~4 environments (Staging, UAT, Demo, Prod). Each Combination of app + environment has its own ApiKey in Seq and the ApiKey is defined as having two attached properties, `App` and `System` (environment). Aside from that there are probably dozens of signals and queries that rely on `App` as well as muscle memory by 30 seq users, so i'd much prefer to avoid that churn.

**Comment by nblumhardt** [comment]
Makes sense, thanks @Suchiman 👍 I'll raise an issue in `seq-tickets` to track.
