### ISSUE TITLE
How to integrate SerilogTracing with Microsoft's ILogger<>

### ISSUE THREAD

**Issue by R4cOOn** [serilog-tracing/serilog-tracing#75]
Hi,

I'm using Serilog with Seq and the new tracing feature looks amazing.

However, all the samples use the static logger (eg. https://nblumhardt.com/2024/01/serilog-tracing/ or https://github.com/liammclennan/serilog-tracing/blob/dev/example/Example.WeatherService/Program.cs).  

I'm using the BootstrapLogger feature and the Microsoft `ILogger<>` logging interface.  
Both of these make the given default setup and configuration not work because the `Log.Logger` static instance isn't really used.

If I set the logging configuration to `preserveStaticLogger: true`  the Bootstrap configuration does not get overwritten and the logs become too verbose.

Could you please provide an example of the integration of `SerilogTracing` with the the `ILogger<>` interface?

Cheers.

**Comment by nblumhardt** [comment]
Hi @R4cOOn, thanks for the note, unfortunately the API has only just started stabilizing so we're a bit short of examples :-)

Can you please share a rough outline of how your Serilog setup looks, e.g. the initialization of the bootstrap logger, and then initialization using `UseSerilog` or `AddSerilog`?

The API should work with bootstrap loggers without needing to do anything special; I think you should avoid `preserveStaticLogger`, though - there's a good chance that would prevent things working as expected.

As for how to create traces in this setup, you'll need to get a Serilog `ILogger` into your components to start spans at this point (it can normally be injected). Not sure what we'll end up doing to support `ILogger<T>`, it's on the radar but we're working our way up the stack from the lowest layers so it hasn't been given any attention yet.

Hope this helps!
Nick

**Comment by R4cOOn** [comment]
Hi @nblumhardt,

Thank you for the very quick reply.  

I took the example from the repository and made it look somewhat like what we have in our production code.  
I created merge request https://github.com/serilog-tracing/serilog-tracing/pull/76 for it (I wasn't sure what would be the most effective way to provide you with a working example).

With my changes, I no longer see most of the logs entries in Seq.  
The original example worked with no issue.

Cheers.

**Comment by nblumhardt** [comment]
Thanks for the extra info, @R4cOOn.

I think you can just remove this section:

```csharp
            services.AddLogging(
                builder =>
                {
                    builder.AddSerilog();
                    _activityConfiguration = new ActivityListenerConfiguration().Instrument.HttpClientRequests().TraceToSharedLogger();
                });
```

There shouldn't be any need to change the activity listener configuration after it's set up, and `services.AddLogging()` will break `services.AddSerilog()` - they're not compatible (one or the other can be used).

Fingers crossed this helps narrow it down 👍

**Comment by nblumhardt** [comment]
Hi @R4cOOn - did the above help?

**Comment by nblumhardt** [comment]
Hi again! I'll close this one assuming you were able to work through/around it; please drop us a line anytime if you need more info. Cheers!

**Comment by R4cOOn** [comment]
Hi @nblumhardt,

Sorry, I had to work on something else and couldn't get to you.  

Thank you for your input.  
It tried it again and could get it to work on the sample project.  
I must have overcomplicated the configuration in my project and broke it.

Thank you for the quick reply.

**Comment by nblumhardt** [comment]
That's great news - thanks @R4cOOn :+1:
