### ISSUE TITLE
MEL `ILogger<T>` does not enrich logs with trace info

### ISSUE THREAD

**Issue by tormodfj** [serilog-tracing/serilog-tracing#90]
I am aware that issues related to _Microsoft.Extensions.Logging_ (MEL) have previously been submitted and closed (#48, #75), and I apologize if this turns out to be a mere duplicate. I suspect, however, that my case is slightly different, and may merit its own discussion.

I work on an ASP.NET application heavily reliant on MEL `ILogger<T>` instances being injected to components. During startup, we call `UseSerilog` with (among other things) the `.WriteTo.Seq(...)` config method. 

Curious about the [new tracing support in Seq](https://docs.datalust.co/docs/whats-new), I decided to try SerilogTracing, simply switching `.WriteTo.Seq` with `.WriteTo.SeqTracing` and adding ASP.NET request instrumentation. This works more or less exactly like advertised, resulting in calls like `Log.ForContext<MyClass>().Information("Testing")` automatically being enriched with trace information, and Seq rendering beautiful trace diagrams of requests to our apps.

However, all my _existing_ logging statements, using MEL's `ILogger<T>`, are seemingly not enriched with any trace information. I am curious as to whether this is due to limitations in MEL, any missing configuration on my part, or if it simply hasn't been implemented yet. I fully respect if the latter is the case.

Further, would it make sense to alter the semantics of `ILogger.BeginScope` when using SerilogTracing? Rather than (or maybe in addition to) [the current Serilog behavior](https://nblumhardt.com/2016/11/ilogger-beginscope/), could this possibly be used to trigger `Log.Logger.StartActivity`?

Many thanks
Tormod

**Comment by nblumhardt** [comment]
Hi Tormod, thanks for reaching out! Is it possible you're running a slightly older version of Serilog.Extensions.Logging? IIRC, trace id correlation support was added there in the 8.0.0 version. Curious whether you might still be on 6.0.0 (and can look at options to backport the feature if so).

**Comment by tormodfj** [comment]
You are absolutely right. I was actually on an even older version of `Serilog.Extensions.Logging` than 6.0.0, transitively via an old version of `Serilog.Extensions.Hosting`. After updating to the latest version, Trace IDs automatically enrich logs through MEL `ILogger<T>`, just as I was hoping.

Any thoughts regarding whether `ILogger.BeginScope` could possibly be utilized to trigger `Log.Logger.StartActivity`?

Thanks again
Tormod

**Comment by tormodfj** [comment]
Thanks a lot for your swift and accurate feedback. I'm closing it now, as my issue was resolved.

Have a great day!
Tormod
