### ISSUE TITLE
GET calls to 'http://169.254.169.254/metadata/instance/compute' appear after using this library

### ISSUE THREAD

**Issue by nabeel-servcorp** [serilog-tracing/serilog-tracing#95]
We have started seeing HTTP GET calls to http://169.254.169.254/metadata/instance/compute in our Seq logs, after we introduced this library for Seq tracing. Why is it so and can it be prevented?

On a side note, all these logs are logged as Error, with no other information available. Screenshot below:

![image](https://github.com/serilog-tracing/serilog-tracing/assets/135291300/77632c19-65b1-46a8-948c-047582a6d991)

**Comment by nblumhardt** [comment]
Using:

```csharp
    .Instrument.WithDefaultInstrumentation(false)
```

will turn off `HttpClient` instrumentation entirely, while leaving everything else intact. As Liam suggested, filtering these particular ones out is likely a better strategy.

The null status code generally means that the request was canceled or an exception thrown - my guess is that the exception is being thrown is caught and suppressed elsewhere in the stack.

**Comment by nabeel-servcorp** [comment]
> Using:
> 
> ```cs
>     .Instrument.WithDefaultInstrumentation(false)
> ```
> 
> will turn off `HttpClient` instrumentation entirely, while leaving everything else intact. As Liam suggested, filtering these particular ones out is likely a better strategy.
> 
> The null status code generally means that the request was canceled or an exception thrown - my guess is that the exception is being thrown is caught and suppressed elsewhere in the stack.

Can you point me to the library code where this particular HTTP GET call happens. I tried digging the source code but couldn't find any reference to the mentioned IP address or the relative URL.

**Comment by nblumhardt** [comment]
SerilogTracing isn't making the HTTP call, it's just recording that the HTTP call is being made. I think that request has something to do with Azure infrastructure, perhaps? It'll be one of the components in your app performing the HTTP request. SerilogTracing is just informing you about it.

**Comment by nabeel-servcorp** [comment]
Thank you @nblumhardt for the pointer.
Those HTTP `GET` calls in my case are due to Azure Application Insights enabled. Disabling it makes the calls disappear as well.

**Comment by pinkfloydx33** [comment]
@nabeel-servcorp  Were you able to figure out how to get QuickPulse heartbeats or `v2/track` calls ignored when using Application Insights? When in "developer mode" it literally just spams non-stop in-a-loop tracking of `v2/track`... have you hit that?

**Comment by nabeel-servcorp** [comment]
> @nabeel-servcorp Were you able to figure out how to get QuickPulse heartbeats or `v2/track` calls ignored when using Application Insights? When in "developer mode" it literally just spams non-stop in-a-loop tracking of `v2/track`... have you hit that?

Yes. Two ways to do that.
1. Add a Seq filter to hide them
2. Use code something like the snippet shown below:
```c#
var aiOptions = new ApplicationInsightsServiceOptions();
// Disables QuickPulse (Live Metrics stream).
aiOptions.EnableQuickPulseMetricStream = false;
services.AddApplicationInsightsTelemetry(aiOptions);
```

**Comment by brendangooden** [comment]
@nabeel-servcorp  - Do you have NewRelic instrumentation / agents installed on your hosts? We are having exactly the same issue and trying to work out what is causing it.

**Comment by nabeel-servcorp** [comment]
> @nabeel-servcorp - Do you have NewRelic instrumentation / agents installed on your hosts? We are having exactly the same issue and trying to work out what is causing it.

No.

**Comment by brendangooden** [comment]
@nabeel-servcorp  Did you end up working out what is causing it or did you just disable `HttpClient` instrumentation?  
Although from what i can see, its being logged via the `AspNetCode` request instrumentation.
