### ISSUE TITLE
Instrumentation.AspNetCore vs. UseSerilogRequestLogging

### ISSUE THREAD

**Issue by Suchiman** [serilog-tracing/serilog-tracing#96]
After procrastinating, experimenting and finally bothering IT to upgrade prod seq, i'm trying to get serious about switching to SerilogTracing.
I've noticed that `Instrument.AspNetCoreRequests` fills the role of SerilogRequestLogging but not quite in the same way.

Currently i'm doing the following:
```csharp
app.Use(async (httpContext, next) =>
{
    // add an enricher that adds request related log event properties from the HttpContext on every log written,
    // including the "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms" event
    httpContext.Items[nameof(QueryStatistics)] = new QueryStatistics();
    using (LogContext.Push(new RequestContextEnricher(httpContext)))
    {
        await next();
    }
});

app.UseSerilogRequestLogging(x =>
{
    // add a bunch of additional properties to the responded event only
    x.EnrichDiagnosticContext = (diags, context) =>
    {
        if (context.Request.QueryString is { HasValue: true, Value: { } query })
            diags.Set("RequestQuery", query);

        if (context.Response.Headers.Location.ToString() is { Length: > 0 } location)
            diags.Set("ResponseLocation", location);

        if (context.RequestAborted.IsCancellationRequested)
            diags.Set("RequestAborted", true);

        if (context.Items[nameof(QueryStatistics)] is QueryStatistics stats && (stats.BytesReceived > 0 || stats.LogicalReads > 0))
            diags.Set(nameof(QueryStatistics), stats, true);
    };

    // also, if this request ended with a canellation exception because the request was canceled, do not log this as error
    x.GetLevel = (context, elapsed, exception) =>
    {
        if (exception != null)
        {
            if (exception is OperationCanceledException && context.RequestAborted.IsCancellationRequested)
            {
                return LogEventLevel.Information;
            }
            return LogEventLevel.Error;
        }
        if (context.Response.StatusCode > 499)
        {
            return LogEventLevel.Error;
        }

        return LogEventLevel.Information;
    };
});
```

and after my experiments with tracing, i've come up with the following, trying to be both backwards compatible while enabling the new distributed tracing features.
```csharp
.Instrument.AspNetCoreRequests(x =>
{
    x.MessageTemplate = "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms";
    x.GetRequestProperties = request =>
    {
        request.HttpContext.Items["RequestTiming"] = Stopwatch.StartNew();
        request.HttpContext.Items[nameof(QueryStatistics)] = new QueryStatistics();

        List<LogEventProperty> props = [];

        props.Add(new LogEventProperty("RequestMethod", new ScalarValue(request.Method)));

        if (request.QueryString is { HasValue: true, Value: { } query })
            props.Add(new LogEventProperty("RequestQuery", new ScalarValue(query)));

        // ...

        return props;
    };
    x.GetResponseProperties = response =>
    {
        List<LogEventProperty> props = [];

        props.Add(new LogEventProperty("StatusCode", new ScalarValue(response.StatusCode)));

        if (response.HttpContext.Items["RequestTiming"] is Stopwatch sw)
            props.Add(new LogEventProperty("Elapsed", new ScalarValue(sw.Elapsed.TotalMilliseconds)));

        if (response.Headers.Location.ToString() is { Length: > 0 } location)
            props.Add(new LogEventProperty("ResponseLocation", new ScalarValue(location)));

        if (response.HttpContext.RequestAborted.IsCancellationRequested)
            props.Add(new LogEventProperty("RequestAborted", new ScalarValue(true)));

        if (response.HttpContext.Items[nameof(QueryStatistics)] is QueryStatistics stats && (stats.BytesReceived > 0 || stats.LogicalReads > 0) && Log.BindProperty(nameof(QueryStatistics), stats, true, out var statProp))
            props.Add(statProp);

        return props;
    };
})
```
although this did not quite work the way i've expected.
Properties added in `GetRequestProperties` are not enriched on other log events written, so i don't quite understand the purpose of the separation between `GetRequestProperties` and `GetResponseProperties` .
Also took me a while to figure out how to produce `LogEventProperty`s  without `ILogEventPropertyFactory`, especially for the deconstruct case.
I can keep using the `RequestContextEnricher` for now, to enrich log events written as before, but unfortunately i had to duplicate its logic for `GetRequestProperties` since that stuff runs earlier now than i can attach the `RequestContextEnricher`.

I did not find a way to override the level though.

Talking about level override, i've also noticed that the Azure Storage libs + HttpClient now show up in the log which is cool, however, while making sense from a certain perspective, HTTP requests with a non success status are being logged on error severity, however, it is expected behavior, that when calling `if (await blob.ExistsAsync())`, that the HEAD sent internally by the storage lib will result in 404 if the file does not exist. This will cloudy the log, where error is currently reserved for some unexpected error that should get fixed. So i could either filter System.Net.Http from the log, try convince microsoft that error level based on status code is a bad idea or ask here to see if there are other options to deal with it.

**Comment by nblumhardt** [comment]
Thanks for all the feedback @Suchiman, this is great 👍 

Duplicating the enricher is unfortunately the only way to do what you are looking for at this point, but I think something like `x.GetEnrichers()` or `x.AddEnricher()` would make it possible to reuse the enricher object out in the instrumentation. Will give this some thought!

I think the ASP.NET Core instrumentation should probably be checking `RequestAborted` and modifying the completion level appropriately, these kinds of events are just noise otherwise.

On the client-side 404 handling, I think this could also be improved in the `HttpClient` instrumentation - either by changing how we decide on the completion level, supporting `Instrument.HttpClientRequests(x => x.GetLevel = ...)`, or `x.Treat4xxAsError = false`. Needs some thought here, too.

**Comment by nblumhardt** [comment]
Hi again! A couple of points addressed with the PRs above, keen to hear whether those make any improvement for you :-)
